---
- name: Listen for alertmanager events
  hosts: all
  sources:
    - benthomasson.eda.alertmanager:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: Andrius's birthday
      condition: event.alert.labels.severity == "event_trigger" and event.alert.status == "firing"
      action:
        debug:
          msg: "Happy Birthday"
