---
- name: Respond to webhook POST
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 8000

  rules:
    - name: PORT UNREACHABLE
      condition: event.payload.error == "unreachable"
      action:
        run_job_template:
          name: "[EDA] Open Port"
          organization: "Automation Everywhere"
          job_args:
            extra_vars:
              eda_host: "{{ event.payload.host }}"
              eda_port: "{{ event.payload.port }}"
