- name: Capture POSTs from gitea
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
      filters:
        - ansible.eda.json_filter:
            exclude_keys: ['sender', 'owner']
        - ansible.eda.dashes_to_underscores:
  rules:
    - name: Debug payload
      condition: true
      action:
        debug:

    - name: IaC - Deploy new VM
      condition: event.body.headers.application == "instruqt" and event.body.body.type == "sandbox.failed"
      action:
        run_job_template:
          name: [AZ] Virtual Machine
          organization: Automation Everywhere
          job_args:
            extra_vars:
              app_name: "{{ event.body.body.track_id }}"
              timestamp: "{{ event.body.body.timestamp }}"
              participant_id: "{{ event.body.body.participant_id }}"
